#!/usr/bin/env bash
#This script connect to server without password
#ssh client is configure to  use the private keys

#PasswordAuthentication no
#IdentityFile ~/.ssh/school

ssh -A ubuntu@3.80.222.106
