#!/usr/bin/env bash
# This script install and configure haproxy.
sudo apt update
sudo apt install haproxy -y
load_balance_config=\
"backend my_servers
        balance roundrobin
        server 4810-web-01 54.242.159.91:80
        server 4810-web-02 34.227.9.170:80
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"
# enable haproxy to be managed by init script
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo $load_balance_config >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
