#!/usr/bin/env bash
#setting up load balancing
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
balance roundrobin
server 4810-web-01 54.242.159.91:80 check
server 4810-web-02 34.227.9.170:80 check
frontend http
bind *:80
mode http
default_backend web-backend'
sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
