#!/usr/bin/env bash
# this function transfers a file from our client to a server

if [$# -lt 4]; then
echo "Usage: 0-transfer_file PATHE_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
file="$1"
host="$2"
username="$3"
private_key="$4"
scp -i "$private_key" -o StrictHostKeyChecking=no "$file" "$username@:~/"$host
fi
