#!/usr/bin/env bash
# this function transfers a file from our client to a server

if [$# -lt 4]; then
echo "Usage: 0-transfer_file PATHE_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i "$4" "$1" "$3@$2" -o StrictHostKeyChecking=no "$file" "$ubuntu@54.242.159.91:~/"$host
fi
